version: '3.2'
services:
  app:
    build: .
    environment:
      - NODE_ENV=production
      - HYSTREETS_API_TOKEN=<API_TOKEN_HERE>
      - ECO_COUNTER_API_TOKEN=<API_TOKEN_HERE>
    ports:
      - 127.0.0.1:5000:3000
  redis:
    image: 'redis:6.0-alpine'
    ports:
      - 127.0.0.1:6379:6379
