version: '3.2'
services:
  app:
    build: .
    environment:
      - NODE_ENV=production
      - HYSTREETS_API_TOKEN=<API_TOKEN_HERE>
      - ECO_COUNTER_API_TOKEN=<API_TOKEN_HERE>
    ports:
      - 3000:3000
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
